Re enable Travis CI Tests

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,6 +10,7 @@ matrix:
               - CMAKE_GENERATOR_NAME="Unix Makefiles"
               - CMAKE_BUILD_TYPE="Debug"
               - CMAKE_TOOLCHAIN_FILE_NAME=android-ndk-r18b-api-21-x86-clang-libcxx.cmake
+              - CTEST_REGEXP="NONE"
         - name: "Android, Release"
           os: linux
           dist: xenial
@@ -18,6 +19,7 @@ matrix:
               - CMAKE_GENERATOR_NAME="Unix Makefiles"
               - CMAKE_BUILD_TYPE="Release"
               - CMAKE_TOOLCHAIN_FILE_NAME=android-ndk-r18b-api-21-x86-clang-libcxx.cmake
+              - CTEST_REGEXP="NONE"
         - name: "Linux, Debug"
           os: linux
           dist: xenial
@@ -26,6 +28,7 @@ matrix:
               - CMAKE_GENERATOR_NAME="Unix Makefiles"
               - CMAKE_BUILD_TYPE="Debug"
               - CMAKE_TOOLCHAIN_FILE_NAME=gcc-cxx14-c11.cmake
+              - CTEST_REGEXP="Tests$"
         - name: "Linux, Release"
           os: linux
           dist: xenial
@@ -34,6 +37,7 @@ matrix:
               - CMAKE_GENERATOR_NAME="Unix Makefiles"
               - CMAKE_BUILD_TYPE="Release"
               - CMAKE_TOOLCHAIN_FILE_NAME=gcc-cxx14-c11.cmake
+              - CTEST_REGEXP="Tests$"
         - name: "macOS, Debug"
           os: osx
           osx_image: xcode10.2
@@ -41,6 +45,7 @@ matrix:
               - CMAKE_GENERATOR_NAME="Unix Makefiles"
               - CMAKE_BUILD_TYPE="Debug"
               - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx14.cmake
+              - CTEST_REGEXP="Tests$"
         - name: "macOS, Release"
           os: osx
           osx_image: xcode10.2
@@ -49,6 +54,10 @@ matrix:
               - CMAKE_BUILD_TYPE="Release"
               - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx14.cmake
               - CTEST_REGEXP="Tests$"
+
+env:
+    global:
+        - CTEST_LOG_REGEXP="=== EVENT \#\|SwappedVector\|\[\([a-zA-Z]\+\)\(\/[a-zA-Z0-9]\+\)\?\]"
 
 addons:
     apt: # Linux
@@ -92,6 +101,7 @@ script:
         -DBUILD_ALL:BOOL=TRUE
         ..
     - cmake --build . --config $CMAKE_BUILD_TYPE -- -j 2
+    - ctest -C $CMAKE_BUILD_TYPE -V -j 2 -R "$CTEST_REGEXP" | grep --line-buffered -i -v "$CTEST_LOG_REGEXP"
     - cpack -C $CMAKE_BUILD_TYPE
 
 deploy:
@@ -106,3 +116,18 @@ deploy:
         tags: true
         condition: $CMAKE_BUILD_TYPE = "Release"
     skip_cleanup: true
+
+after_success:
+    - |
+        if [ "$CMAKE_TOOLCHAIN_FILE_NAME" = "android-ndk-r18b-api-21-x86-clang-libcxx.cmake" ]; then
+            echo "TODO: Fix and run tests for Android and remove this 'if' statement."
+        elif [ "$CMAKE_BUILD_TYPE" = "Release" ]; then
+            echo "Code-coverage is only available for debug builds. Skipping..."
+        else
+            COVERAGE_FILE="$TRAVIS_BUILD_DIR/build/coverage.info"
+            echo "coverage.info: $COVERAGE_FILE"
+            lcov --capture --directory . --output-file $COVERAGE_FILE
+            lcov --remove $COVERAGE_FILE "/Applications/Xcode*" "/usr/*" "*/boost/*" "*/gtest/*" "*/tests/*" "*/_ExternalProjects/*" --output-file $COVERAGE_FILE
+            lcov --list $COVERAGE_FILE
+            bash <(curl -s https://codecov.io/bash) -f $COVERAGE_FILE || echo "Upload to codecov.io FAILED"
+        fi
